// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Addnums(arg1:Array<number>):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function Zonetime(arg1:string):Promise<string>;
