// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Addnums(arg1) {
  return window['go']['main']['App']['Addnums'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Zonetime(arg1) {
  return window['go']['main']['App']['Zonetime'](arg1);
}
